[project]
name = "tiny-market"

[contracts.paul-nft]
path = "contracts/paul-nft.clar"

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"

[contracts.paul-coin]
path = "contracts/paul-coin.clar"

[contracts.sip010-ft-trait]
path = "contracts/sip010-ft-trait.clar"

[contracts.tiny-market]
path = "contracts/tiny-market.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
